version: '3'

services:
  line-liff:
    build: .
    image: line-liff/app
    command: yarn dev
    volumes:
      - "./__mocks__:/usr/src/app/__mocks__"
      - "./__tests__:/usr/src/app/__tests__"
      - "./components:/usr/src/app/components"
      - "./pages:/usr/src/app/pages"
      - "./public:/usr/src/app/public"
      - "./styles:/usr/src/app/styles"
      - "./utils:/usr/src/app/utils"
      - "./server:/usr/src/app/server"
    environment:
      DATABASE_URL: "line-liff-postgres"
      DATABASE_NAME: "line-liff"
      DATABASE_USERNAME: "api"
      DATABASE_PASSWORD: "api"
    ports:
      - "3000:3000"
    depends_on: 
      - line-liff-postgres
    networks:
      - line-liff
  line-liff-postgres:
    image: postgres:9.6
    volumes:
      - "line-liff-postgres-db:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "api"
      POSTGRES_DB: "line-liff"
    networks:
      - line-liff
volumes:
  line-liff-postgres-db:
  line-liff-node_modules:
networks:
  line-liff:

