version: '3'

services:
  line-liff:
    build: .
    image: line-liff/app
    command: yarn dev
    volumes:
      - "./__mocks__:/usr/src/app/__mocks__"
      - "./__tests__:/usr/src/app/__tests__"
      - "./components:/usr/src/app/components"
      - "./pages:/usr/src/app/pages"
      - "./public:/usr/src/app/public"
      - "./styles:/usr/src/app/styles"
      - "./utils:/usr/src/app/utils"
      - "./server:/usr/src/app/server"
      - "./services:/usr/src/app/services"
      - "./web-config:/usr/src/app/web-config"
      - ".env:/usr/src/app/.env"
      - "./contexts:/usr/src/app/contexts"
    environment:
      DATABASE_HOST: "line-liff-postgres"
      DATABASE_NAME: "line-liff"
      DATABASE_USERNAME: "api"
      DATABASE_PASSWORD: "api"
      DATABASE_PORT: "5432"
      DATABASE_DIALECT: "postgres"
      SERVER_ENDPOINT_HOST: "localhost"
      SERVER_ENDPOINT_SCHEME: "http"
      NODE_ENV: "development"
      PORT: 3000
      ASSET_PREFIX: ""
      API_PREFIX: "http://localhost:3000/api"
      SERVER_OPEN_SWAGGER: "true"
      AXIOS_TIMEOUT: 50000
      LIFF_ID: '1653655380-2GWbJ4NN'
      SSE_GET_PRODUCT_EVENT: 'get-all-products'
      SSE_GET_ORDER_EVENT: 'get-all-orders'
    ports:
      - "3000:3000"
    depends_on: 
      - line-liff-postgres
    networks:
      - line-liff
  line-liff-postgres:
    image: postgres:9.6
    volumes:
      - "line-liff-postgres-db:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "api"
      POSTGRES_DB: "line-liff"
    networks:
      - line-liff
volumes:
  line-liff-postgres-db:
  line-liff-node_modules:
networks:
  line-liff:

